### ISSUE TITLE
everyone claim an SCRQ!

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/condition-reports#2]
Please claim a "Specific Condition Report Question" from pg 7 of the [Specific Condition Report Guidance pdf](https://github.com/USF-IMARS/condition-reports/blob/master/2018-condition-report-guidance.pdf). The SCRQs are below too:

1. What are the states of influential human drivers and how are they changing?
2. What are the levels of human activities that may adversely influence water quality and how are they changing?
3. What are the levels of human activities that may adversely influence habitats and how are they changing?
4. What are the levels of human activities that may adversely influence living resource quality and how are they changing?
5. What are the levels of human activities that may adversely influence maritime archaeological resource quality and how are
they changing?
6. **What is the eutrophic condition of sanctuary waters and how is it changing?**
7. Do sanctuary waters pose risks to human health and how are they changing?
8. Have recent changes in climate altered water conditions and how are they changing?
9. Are other stressors, individually or in combination, affecting water quality, and how are they changing?
10. **What is the integrity of major habitat types and how is it changing?**
11. What are contaminant concentrations in sanctuary habitats and how are they changing?
Living Resources
12. **What is the status of keystone and foundation species and how is it changing?**
13. **What is the status of other focal species and how is it changing?**
14. **What is the status of non-indigenous species and how is it changing?**
15. What is the status of biodiversity and how is it changing?
Maritime Archaeological Resources
16. What is the archaeological integrity of known maritime archaeological resources and how is it changing?
17. Do known maritime archaeological resources pose an environmental hazard and how is this threat changing?

Please comment here with your choice & try to create a (`.md`) page for your SCRQ. Those will become web pages & we will edit them next week to add content and (hopefully) data.

**Comment by 7yl4r** [comment]
On Wednesday or Thursday this week I am going to create any missing pages & add questions from @mhepner90 's [management questions document](https://github.com/USF-IMARS/condition-reports/blob/master/Potential%20Management%20Questions%20for%20the%20portal_Hepner.docx).

**Comment by cjrmbon** [comment]
CJ will attempt to make a page for Q12 What is the status of keystone and foundation species and how is it changing? I will use several datsets from the MBON Florida portal catalog
